### PR TITLE
Update libc.jl

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
This is a clean nonbreaking way to support using either localtime_r or gmtime_r.

I like being able to get the current time as a string with minimal fuss,
if you feel it worthwhile, please add these two lines:
strftime(fmt::AbstractString, utc=false::Bool) = strftime(fmt, time(), utc)
strftime(utc=false::Bool) = strftime("%c", time(), utc)
 
I did not understand  why there was the catchall signature strftime(t), and took it out --
if it serves a purpose, please add:  strftime(t, utc=false::Bool) = strftime("%c", t, utc)

### CODE REVIEW

**Comment by yuyichao** [comment]
Just curious. Did you mean to submit this as a PR to base julia or is this only for your own reference...

**Comment by JeffreySarnoff** [comment]
The changes that I made to libc.jl address a #todo that has been in the file for a long time, and I thought would be found agreeable.  The change in with my note that introduces to strftime using the current time when no time is given is one I favor; not knowing the working perspective on introducing default handling, I put it in the note so it is available to be copied into this request before being pulled, if others felt it beneficial.  Similarly, forcing an error when strftime is given an argument that is not appropriate seems better than absorbing it as if it were calling strftime(); since it had been in the file, I did not want to remove it without noting that there may be some reason to have that I do not know.

**Comment by JeffreySarnoff** [comment]
(or, more succinctly) I meant to submit it as a PR to base julia.

**Comment by JeffreySarnoff** [comment]
My thinking on this has evolved.

**Pull request closed without merging**
